config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users
  resources :books
  get '/' => 'books#top', as: 'top'
  get '/about' => 'books#about', as: 'about'
  # post '/books/:id' => 'books#index'
  # get '/books/index' => 'books#index', as: 'books_index'
  root 'books#top'
  # get '/home' => 'users#home', as: 'home'
  delete '/books/:id' => 'books#destroy', as: 'destroy_book'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :body, length: { in: 1..200 }
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
  attachment :user_image
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery with: :exception
 before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
 devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
 devise_parameter_sanitizer.permit(:sign_in, keys: [:name,:email])
 end
private
def after_sign_out_path_for(resource_or_scope)
      top_path
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:create, :index, :show, :edit, :update, :destroy]

  def top
    if user_signed_in?
       redirect_to user_path(current_user)
    end
  end
  def create
  	  @book = Book.new(book_params)
      @user = current_user
      @books = Book.all.order(created_at: :ASC)
      @book.user_id = current_user.id
      # bookモデルのuser_idカラムにログインuserのidを入れている。入れないとshowアクションで紐付かない
  	  if @book.save
      # リダイレクト先を本の詳細にしています(どの本の詳細か指定しています)
  	  redirect_to book_path(@book.id)
      else
      render 'index'
      end
  end

  def about
  end

  def index
  	  @book = Book.new
      @books = Book.all.order(created_at: :ASC)
      @user = current_user
      @users = User.all
  end

  def show
      @book_id = Book.find(params[:id])
      @user = @book_id.user
      @book = Book.new
  end

  def edit
      @book = Book.find(params[:id])
      if @book.user_id != current_user.id
         redirect_to books_path
      end
  end

  def update
      @book = Book.find(params[:id])
      @book.update(book_params)
      redirect_to book_path(@book)
  end

  def destroy
      book = Book.find(params[:id])
      book.destroy
      redirect_to books_path
  end

  private
  def book_params
  	  params.require(:book).permit(:title, :body)
  end

  def user_params
      params.require(:user).permit(:name, :introduction)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :index, :edit, :update]
  # def home
  	  # @book = Book.new
      # @user = current_user
      # @book.user_id = @user.id
      # @books = @user.books
  # end

  def new
  end

  def create
  	  # book = book.new(book_params)
     #  book.save
     #  redirect_to '/books/index'
  end

  def show
      @book = Book.new
      @user = User.find(params[:id])
      @book.user_id = @user.id
      @books = @user.books
  end
  def index
      @user = current_user
  	  @book = Book.new
      @users = User.all
  end

  def edit
      @book = Book.new
      @user = User.find(params[:id])
      @books = @user.books
      if @user != current_user
         redirect_to user_path(current_user)
      end
      @user = User.find(params[:id])
  end

  def update
      @user = current_user
      @user.update(user_params)
      redirect_to user_path(current_user)
  end

  private
  def user_params
      params.require(:user).permit(:name, :introduction, :user_image)
  end

  def book_params
  	  params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/about.html.erb
<div class="container">
 <div class="row">
   <div class="col-lg-1"></div>
   <div class="col-lg-10">
<h1><strong>welcome to <span class="glyphicon glyphicon-book"></span>Bookers </strong>!!</h1>
   </div>
   <div class="col-lg-1"></div>
 </div>
</div>

app/views/books/edit.html.erb
<div class="book-edit">
	<div class="book-edit-box">
<h1>Editing Book</h1>
<%= form_for (@book) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :opinion, "Opinion (200 Character limit)" %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit "Update book", class:"create_book_btn" %>
  </p>
<% end %>
    </div>
    <%= link_to "Show ", book_path(@book) %>|<%= link_to " Back", books_path() %>
</div>

app/views/books/index.html.erb
<div class="container">
<div class="row">
<div class="col-lg-3">
<div class="user-info">
    <h2>User info</h2>
    <!-- :fillでは、投稿された画像の縦横の大きさを指定しています。単位はpxです。(fallbackだと適用されず指定している画像の大きさで表示されます）refileの仕様により、_idを外した状態でカラムを指定しています。 -->
    <% if @user.user_image.present? %>
       <%= attachment_image_tag @user, :user_image, :fill, 200, 200 %>
    <% else %>
       <%= image_tag 'no_image.jpg', size: '200x200' %>
    <% end %>
    <div class="user-name-box">
      <div class="user-name-title">
        <p class="name">name</p>
      </div>
      <div class="user-name-current">
        <p class="name"><%= @user.name %></p>
      </div>
    </div>
    <div class="user-introduction-box">
      <div class="user-introduction-title">
        <p class="introduction">introduction</p>
      </div>
      <div class="user-introduction-current">
        <p class="introduction"><%= @user.introduction %></p>
      </div>
    </div>
    <div class="user-introduction"></div>
    <div class="user-info-edit">
<%= link_to(edit_user_path(@user.id)) do %><button type="button" class="btn btn-default btn-sm wrench"><span class="glyphicon glyphicon-wrench"></span></button><% end %>
     </div>
</div>
<h2>New book</h2>
<%= form_for (@book) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :opinion, "Opinion (200 Character limit)"  %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit "Create book", class:"create_book_btn" %>
  </p>
<% end %>
</div>
<div class="col-lg-9">
<h2>Books</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Title (Please click here!!)</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
       <%= attachment_image_tag book.user, :user_image, :fill, 50, 50, fallback: 'no_image.jpg', :size => '50x50' %>
    </td>
        <td><%= link_to "#{book.title}", book_path(book.id), class: "show_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
<div class="row">
<div class="col-lg-3">
<div class="user-info">
	  <h2>User info</h2>
    <!-- :fillでは、投稿された画像の縦横の大きさを指定しています。単位はpxです。(fallbackだと適用されず指定している画像の大きさで表示されます）refileの仕様により、_idを外した状態でカラムを指定しています。 -->
    <%= attachment_image_tag @user, :user_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    <div class="user-name-box">
      <div class="user-name-title">
        <p class="name">name</p>
      </div>
      <div class="user-name-current">
        <p class="name"><%= @user.name %></p>
      </div>
    </div>
    <div class="user-introduction-box">
      <div class="user-introduction-title">
        <p class="introduction">introduction</p>
      </div>
      <div class="user-introduction-current">
        <p class="introduction"><%= @user.introduction %></p>
      </div>
    </div>
    <div class="user-info-edit">
<%= link_to(edit_user_path(@user.id)) do %><button type="button" class="btn btn-default btn-sm wrench"><span class="glyphicon glyphicon-wrench"></span></button><% end %>
     </div>
</div>
<h2>New book</h2>
<%= form_for (@book) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :opinion, "Opinion (200 Character limit)" %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit "Create book", class:"create_book_btn" %>
  </p>
<% end %>
</div>
<div class="col-lg-9">
<h2>Book detail</h2>

<% if @user == current_user %>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= attachment_image_tag @user, :user_image, :fill, 50, 50, format: 'jpeg', fallback: "no-image-icon.jpg" %>
            <%= link_to "#{@user.name}", user_path(@user) %></td>
        <td><%= @book_id.title %></td>
        <td><%= @book_id.body %></td>
        <td><%= link_to(edit_book_path(@book_id)) do %><button type="button" class="btn-success book-show">Edit</button><% end %></td>
        <td><%= link_to(destroy_book_path(@book_id), method: :delete, "data-confirm" => "本当に消しますか？") do %><button type="button" class="btn-danger book-show">Destroy</button><% end %></td>
       </tr>
  </tbody>
</table>

<% else %>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= attachment_image_tag @user, :user_image, :fill, 50, 50, format: 'jpeg', fallback: "no-image-icon.jpg" %>
            <%= link_to "#{@user.name}", user_path(@user.id) %></td>
        <td><%= @book_id.title %></td>
        <td><%= @book_id.body %></td>
      </tr>
  </tbody>
</table>

<% end %>

</div>
</div>
</div>

app/views/books/top.html.erb
<div class="main">
		<h1><strong>welcome to <span class="glyphicon glyphicon-book top-book-icon"></span>Bookers </strong>!!</h1>
		<p>In<span class="glyphicon glyphicon-book top-book-icon"></span><strong>Bookers,</strong></p>
		<p>you can share and exchange your opinions , inpressions , and emotions about varioius books!</p>
</div>
<div class="devise">
<div><button type="button" class="btn btn-info"><span class="s-b"><%= link_to 'Log in', new_user_session_path %></span></button></div>
<div><button type="button" class="btn btn-success"><span class="s-b"><%= link_to 'Sign Up', new_user_registration_path %></span></button></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
<header>
 <div class="container">
 <div class="row">
   <div class="col-lg-1"></div>
   <div class="col-lg-10">
    <div class="header-logo">Bookers</div>
  <div class="header-list">
    <ul>
       <% if user_signed_in? %>
        <li><div><span class="glyphicon glyphicon-home"></span><%= link_to 'Home', user_path(current_user) %></div></li>
      <li><span class="glyphicon glyphicon-user"></span><%= link_to 'Users', users_path %></li>
      <li><span class="glyphicon glyphicon-book"></span><%= link_to 'Books', books_path %></li>
      <li><span class="glyphicon glyphicon-log-out"></span><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
       <% else %>
      <li><div><span class="glyphicon glyphicon-home"></span><%= link_to 'Home', root_path %></div></li>
      <li><span class="glyphicon glyphicon-link"></span><%= link_to 'About', about_path %></li>
      <li><span class="glyphicon glyphicon-edit"></span><%= link_to 'sign up', new_user_registration_path %></li>
      <li><span class="glyphicon glyphicon-log-in"></span><%= link_to 'login', new_user_session_path %></li>
       <% end %>
    </ul>
  </div>
    </div>
    <div class="col-lg-1"></div>
 </div>
 </div>
</header>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>
    <%= yield %>
<footer>
 <div class="container">
 <div class="row">
   <div class="col-lg-2"></div>
   <div class="col-lg-8">
  <div class="footer-text">CopyRight Infratop.inc</div>
   </div>
   <div class="col-lg-2"></div>
 </div>
 </div>
</footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
<div class="row">
<div class="col-lg-1"></div>
<div class="col-lg-11">
<h2>User info</h2>
<%= form_for (@user) do |f| %>
  <p>
   <%= f.label :name, "Name (20 Character limit)" %>
   <%= f.text_field :name %>
  </p>
    <%= f.attachment_field :user_image %>
  <p>
    <%= f.label :introduction, "Introduction (50 Character limit)" %>
    <%= f.text_area :introduction %>
  </p>
  <p>
    <%= f.submit "Update User" %>
  </p>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="row">
<div class="col-lg-3">
<div class="user-info">
    <h2>User info</h2>
    <!-- :fillでは、投稿された画像の縦横の大きさを指定しています。単位はpxです。(fallbackだと適用されず指定している画像の大きさで表示されます）refileの仕様により、_idを外した状態でカラムを指定しています。 -->
    <% if @user.user_image.present? %>
       <%= attachment_image_tag @user, :user_image, :fill, 200, 200 %>
    <% else %>
       <%= image_tag 'no_image.jpg', size: '100x100' %>
    <% end %>
    <div class="user-name-box">
      <div class="user-name-title">
        <p class="name">name</p>
      </div>
      <div class="user-name-current">
        <p class="name"><%= @user.name %></p>
      </div>
    </div>
    <div class="user-introduction-box">
      <div class="user-introduction-title">
        <p class="introduction">introduction</p>
      </div>
      <div class="user-introduction-current">
        <p class="introduction"><%= @user.introduction %></p>
      </div>
    </div>
    <div class="user-introduction"></div>
    <div class="user-info-edit">
<%= link_to(edit_user_path(@user.id)) do %><button type="button" class="btn btn-default btn-sm wrench"><span class="glyphicon glyphicon-wrench"></span></button><% end %>
     </div>
</div>
<h2>New book</h2>
<%= form_for (@book) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :opinion, "Opinion (200 Character limit)"  %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit "Create book", class:"create_book_btn" %>
  </p>
<% end %>
</div>
<div class="col-lg-9">
<h2>Users</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>image
      <th>name
      <th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :user_image, :fill, 50, 50, fallback: 'no_image.jpg', :size => '50x50' %>
    </td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row">
<div class="col-lg-3">
<div class="user-info">
	  <h2>User info</h2>
    <!-- :fillでは、投稿された画像の縦横の大きさを指定しています。単位はpxです。 -->

    <% if @user.user_image.present? %>
       <%= attachment_image_tag @user, :user_image, :fill, 200, 200 %>
    <% else %>
       <%= image_tag 'no_image.jpg', size: '200x200' %>
    <% end %>



    <div class="user-name-box">
      <div class="user-name-title">
        <p class="name">name</p>
      </div>
      <div class="user-name-current">
        <p class="name"><%= @user.name %></p>
      </div>
    </div>
    <div class="user-introduction-box">
      <div class="user-introduction-title">
        <p class="introduction">introduction</p>
      </div>
      <div class="user-introduction-current">
        <p class="introduction"><%= @user.introduction %></p>
      </div>
    </div>
    <div class="user-info-edit">
<%= link_to(edit_user_path(@user.id)) do %><button type="button" class="btn btn-default btn-sm wrench"><span class="glyphicon glyphicon-wrench"></span></button><% end %>
     </div>
</div>
<h2>New book</h2>
<%= form_for (@book) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :opinion, "Opinion (200 Character limit)" %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit "Create book", class:"create_book_btn" %>
  </p>
<% end %>
</div>
<div class="col-lg-9">
<h2>Books</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><% if @user.user_image.present? %>
       <%= attachment_image_tag @user, :user_image, :fill, 50, 50 %>
    <% else %>
       <%= image_tag 'no-image-icon.jpg', size: '50x50' %>
    <% end %></td>
        <td><%= link_to "#{book.title}", book_path(book.id), class: "show_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>